import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./_components/Navbar";
import Searchbar from "./_components/Searchbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="grid lg:grid-flow-col lg:grid-cols-[150px_minmax(900px,_1fr)]">
          <Navbar/>
          <main>
            <div className="lg:py-5">
              <Searchbar/>
            </div>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
